[package]
name = "xml_reader"
version = "0.1.0"
authors = ["tarpaha <ppopchikovsky@gmail.com>"]
edition = "2018"

[dependencies]
quick-xml = "0.12.0"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "bench_iteration"
harness = false
